# permissions for end users to edit itautomationallinones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: itautomationallinone-editor-role
rules:
- apiGroups:
  - ita-all-in-one.ita.exastro
  resources:
  - itautomationallinones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ita-all-in-one.ita.exastro
  resources:
  - itautomationallinones/status
  verbs:
  - get
