# permissions for end users to view itautomationallinones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: itautomationallinone-viewer-role
rules:
- apiGroups:
  - ita-all-in-one.ita.exastro
  resources:
  - itautomationallinones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ita-all-in-one.ita.exastro
  resources:
  - itautomationallinones/status
  verbs:
  - get
