apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ita001
  name: ita001
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ita001
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ita001
    spec:
      containers:
        - image: exastro/it-automation:1.5.0-ja
          name: ita001
#          ports:
#            - containerPort: 10080
#            - containerPort: 10443
          resources: {}
          securityContext:
            privileged: true
          command: ["sh", "-c", "sleep 3600;"] 
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-claim0
#            # - mountPath: /var/lib/mysql
#            #   name: datastore
#           - mountPath: /mnt/exastro
#              name: webdatastore
      initContainers:
        - image: exastro/it-automation:1.5.0-ja
          name: ita001-init
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-claim0
          command: ["sh", "-c", "echo 123 >> /var/lib/registry/a.txt; sleep 10;"] 
      restartPolicy: Always
      volumes:
        - name: registry-claim0
          persistentVolumeClaim:
            claimName: registry-claim0
status: {}
