name: Build and push
on:
  workflow_dispatch:
env:
  EXASTRO_ITA_OPERATOR_IMAGE_NAME: it-automation-operator
  EXASTRO_ITA_OPERATOR_VERSION: '0.0.1'
  EXASTRO_ITA_GOLANG_VERSION: '1.15'

jobs:
  build_and_push_image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.EXASTRO_ITA_GOLANG_VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Environment variables for Makefile
        run: |
          echo "IMG=ghcr.io/${{ github.repository_owner }}/it-automation-operator:$EXASTRO_ITA_OPERATOR_VERSION" >> $GITHUB_ENV
          echo "VERSION=$EXASTRO_ITA_OPERATOR_VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          make docker-build

      - name: Push
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login --username "${{ github.repository_owner }}" --password-stdin ghcr.io
          make docker-push
